### ISSUE TITLE
Refreshing the dashboard takes you to the landing page

### ISSUE THREAD

**Issue by alimojiz1** [Cloudkibo/KiboPush_Support#1]
Refreshing the dashboard or any other page takes you to the landing page. You have to re-login (click log in with facebook) to access your account. Please check.

**Comment by sojharo** [comment]
Thanks for opening this issue. Our team is working on this issue and we would let you know when it is fixed here.

**Comment by sojharo** [comment]
This issue has been fixed now. We can close the issue.

**Comment by jekram** [comment]
@alimojiz1  Please confirm if this has been fixed to your satisfaction. I am closing this now, and we would reopen it based your feedback.
